package com.dscorp.ispadmin.presentation.ui.features.report

enum class DownloadDocumentType {
    DEBTORS_CUT_OFF_CANDIDATES,
    DEBTORS_WITH_ACTIVE_SERVICE,
    DEBTORS_WITH_CANCELLED_SERVICE,
    WITH_PAYMENT_COMMITMENT,
    SUSPENDED,
    CUT_OFF,
    DEBTORS_FROM_PAST_MONTH,
    CANCELLED_SUBSCRIPTIONS_FROM_CURRENT_MONTH,
    CANCELLED_SUBSCRIPTIONS_FROM_PAST_MONTH,
}